name: Secret Brave Key Test

on: [push]

jobs:
  show_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Brave Key
        run: echo "The secret is $SECRET_BRAVE_KEY"
        env:
          SECRET_BRAVE_KEY: ${{ secrets.SECRET_BRAVE_KEY }}
      - name: test
        run: echo runnujem random komandu ovde

